### ISSUE TITLE
IClientShortcuts breaks ESP

### ISSUE THREAD

**Issue by T-Maxxx** [m4dEngi/open-steamworks#3]
Hi. Nice fork ;D
[Windows, Stable Steam]

Unfortunately, met situation where I can not use IClientShortcuts interface in my program. Calling any function from it will cause next error: 
![image](https://user-images.githubusercontent.com/7836454/33014624-f183e004-cdf8-11e7-8188-ff683144a0d4.png)

The code is:
```C++
auto pClientShortcuts = (IClientShortcuts*)pClientEngine->GetIClientApps(hPipe, hUser, CLIENTSHORTCUTS_INTERFACE_VERSION);
    if (!pClientShortcuts)
    {
        cerr << "Unable to get Steam Client Shortcuts Interface" << endl;
        pClientEngine->ReleaseUser(hPipe, hUser);
        pClientEngine->BReleaseSteamPipe(hPipe);
        pClientEngine->BShutdownIfAllPipesClosed();
        return 1;
    }

    //AppId_t appID = parentID;
    AppId_t appID = pClientShortcuts->GetUniqueLocalAppId();
```
The call always returns (uint)(-1) value no matter if I have launched my app through Steam shortcut or directly using EXE.
Interface class seems correct according to latest steamclient.dll and steamclient.dylib. (I meant position of virtual functions in steamclient's maps and in interface class).

Thank you.

**Comment by Ne3tCode** [comment]
Try to call `GetIClientShortcuts` instead of `GetIClientApps` ;)

**Comment by m4dEngi** [comment]
So in fact you were calling GetAppData on IClientApps with no arguments and ended up with corrupted stack.

**Comment by T-Maxxx** [comment]
OMG guys I didn't even noticed that. You rock! 🥇 
I'm sure this was because I have copied a lot of blocks like that with changing member and interface version!
